# SPDX-FileCopyrightText: Copyright 2022 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  app:
    container_name: opal-listener
    build:
      context: .
      args:
        - NODE_ENV=dev
    environment:
      - TZ=EST5EDT
    env_file:
      - .env
    volumes:
      - ./certs:/certs
      - ./listener:/app/listener
      - ./legacy-registration:/app/legacy-registration
      - ./src:/app/src
    command: npm run watch:docker
