version: '3'

services:
  app:
    container_name: opal-listener
    image: opalmedapps/listener:latest
    ports:
      - 8080:80
    volumes:
      - $PWD/listener:/app
      - /app/node_modules
      - /app/config
    command: npm run watch