version: '3'

services:
  app:
    container_name: opal-listener
    image: opalmedapps/listener:latest
    build: .
    environment:
      - TZ=EST5EDT
    volumes:
      - ./listener:/app/listener
      - ./legacy-registration:/app/legacy-registration
      - ./src:/app/src
    command: npm run watch:docker
