version: '3'

services:
  app:
    container_name: opal-listener
    image: opalmedapps/listener:latest
    build: .
    ports:
      - 8080:80
    volumes:
      - $PWD/listener:/app
    command: npm run watch