# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: CI

on:
  push:
    branches:
      - main
      - SB.test-coverage # TODO testing
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-eslint:
    if: false # TODO testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install GitHub Actions formatter
        run: npm install eslint-formatter-gha --no-save
      - name: Print eslint version
        run: npx eslint --version
      - name: Run eslint
        run: npx eslint --format gha

  lint-pre-commit:
    if: false # TODO testing
    uses: opalmedapps/actions/.github/workflows/prek.yaml@main
    with:
      skip: reuse-lint-file

  run-reuse-workflow:
    if: false # TODO testing
    uses: opalmedapps/.github/.github/workflows/reuse.yaml@main

  check-thirdparty-notice:
    if: false # TODO testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: opalmedapps/actions/actions/check-thirdparty-notice@main
        with:
          package-file: './package.json'

  test:
    runs-on: ubuntu-latest
    strategy:
      # Continue the matrix even if one part fails; e.g. continue running new tests even if there's a failure in legacy tests
      fail-fast: false
      matrix:
        part: [ new, legacy ]
        include:
          # Tests for the non-legacy part of the listener (src folder)
          - part: new
            COVERAGE_FLAGS: '--all --src src --include src'
            TEST_PATH_GLOB: './src/**/*.test.*'
            COVERAGE_REPORT_NAME: coverage-report-new
          # Tests for the legacy part of the listener
          - part: legacy
            COVERAGE_FLAGS: '--all --exclude src --exclude eslint.config.js'
            TEST_PATH_GLOB: './{listener,legacy-registration}/**/*.test.*'
            COVERAGE_REPORT_NAME: coverage-report-legacy
    steps:
      # Setup
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - name: Print mocha version
        run: npx mocha --version

      # Run tests and get a coverage report for the next job
      - name: Run tests
        run: |
          npx c8 --reporter cobertura $COVERAGE_FLAGS mocha --reporter json --reporter-option output=mocha-report.json "$TEST_PATH_GLOB"
        env:
          COVERAGE_FLAGS: ${{ matrix.COVERAGE_FLAGS }}
          TEST_PATH_GLOB: ${{ matrix.TEST_PATH_GLOB }}

      # Format the test output for GitHub
      - name: Report test results
        uses: dorny/test-reporter@b082adf0eced0765477756c2a610396589b8c637 # v2.5.0
        # Run this step even if a previous step failed
        if: ${{ !cancelled() }}
        with:
          name: Mocha Tests
          path: mocha-report.json
          reporter: mocha-json

      # Pass the coverage report to the next job
      - name: Archive coverage report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        # Run this step even if a previous step failed
        if: ${{ !cancelled() }}
        with:
          name: ${{ matrix.COVERAGE_REPORT_NAME }}
          path: coverage/cobertura-coverage.xml

  coverage:
    runs-on: ubuntu-latest
    # Always run after the test jobs, even if some tests failed
    if: ${{ always() }}
    needs: [ test ]
    strategy:
      # Continue the matrix even if one part fails
      fail-fast: false
      matrix:
        part: [ new, legacy ]
        include:
          # Coverage for the non-legacy part of the listener (src folder)
          - part: new
            COVERAGE_REPORT_NAME: coverage-report-new
          # Coverage for the legacy part of the listener
          - part: legacy
            COVERAGE_REPORT_NAME: coverage-report-legacy
    steps:
      # Setup
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - name: Print c8 version
        run: npx c8 --version

      # Download the coverage report from the previous job
      - name: Download coverage report
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ matrix.COVERAGE_REPORT_NAME }}
          run-id: ${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Format the coverage output for GitHub
      - name: Report coverage results
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        # Run this step even if a previous step failed
        if: ${{ !cancelled() }}
        with:
          filename: cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
      - name: Add the coverage report to the job summary
        # Run this step even if a previous step failed
        if: ${{ !cancelled() }}
        run: cat code-coverage-results.md >> "$GITHUB_STEP_SUMMARY"

  build-image:
    if: false # TODO testing
    needs: [lint-eslint, lint-pre-commit, coverage]
    permissions:
      contents: read
      packages: write
    uses: opalmedapps/.github/.github/workflows/docker-build.yaml@main
    with:
      test-command: node /app/src/utility/version
